### ISSUE TITLE
Individual Property Data Type

### ISSUE THREAD

**Issue by Anmirazik** [hj91/node-red-contrib-data-validator#1]
Hello , I found this node and have been using it quite extensively and this node has been helping me so far , But i think it can be furthered improve by adding a features where we can validate the data type of the individual property of a json object , I would visualize the UI of the node would looks something like the change node where we can type our own msg path and beneath that it have a selector where we can select the data type of that individual property within the json object , what are your thoughts ? Thanks

**Comment by hj91** [comment]
The main purpose of this node is to quickly validate basic js data types to prevent wrong input getting processed. 

I would recommend you to use standard node-red json node to create json objects and then pass that input to this node - 

eg - if your msg.payload has this structure - person = {name : "harry", age : 25, location : "India"} then use standard function node to access it like 

```javascript
var a = person.name;
msg.payload = a;

return (msg);
```

Then feed this output to data-validation node and get appropriate result. 

If your requirement is different then this, kindly drop me mail regarding it. I will check it in detail.
